language: java
before_install:
  - pip install --user codecov
after_success:
  - codecov
notifications:
  email:
    recipients:
      - cvarela@dattack.com
    on_success: always
    on_failure: always
