language: java
jdk:
  - oraclejdk8
  - oraclejdk7
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - dev@dattack.com
    on_success: always
    on_failure: always
